import { LexShell } from '@/components/lex/LexShell';

const topCards = [
  { title: 'Milestones', value: 176, subtitle: 'Internal deliverables', accent: 'red', breakdown: ['47 red', '4 yellow', '125 green'] },
  { title: 'Court Deadlines', value: 638, subtitle: 'Filings, motions, discovery', accent: 'red', breakdown: ['57 red', '15 yellow', '566 green'] },
  { title: 'Hearings & Mediations', value: 10, subtitle: 'Next 30 days', accent: 'green', breakdown: ['0 red', '0 yellow', '10 green'] },
  { title: 'All cases health', value: 60, subtitle: 'Active cases', accent: 'amber', breakdown: ['29 red', '2 yellow', '29 green'] },
  { title: 'Alerts · last 30 days', value: 101, subtitle: 'Peak this month: 120', accent: 'plain', breakdown: ['101 red today', '19 yellow'] },
  { title: 'Cases by lawyer', value: 60, subtitle: 'Cases', accent: 'blue', breakdown: ['Elena 11', 'Sarah 11', 'James 9', 'Marcus 7', 'David 7', 'Priya 6', 'Aaron 6', 'Margaret 3'] }
] as const;
const capacity = [['Elena Vasquez',95],['Sarah Kim',94],['James O’Connor',91],['Marcus Johnson',86],['David Rodriguez',84],['Priya Patel',80],['Aaron Liu',74],['Margaret Chen',49]] as const;
const accountability = [['Marcus Johnson','Need discovery response assignment confirmed','2 open · 1 overdue'],['Elena Vasquez','Awaiting review on injunction draft','1 open'],['Jasmin Lee','Binder request from client still pending','2 open'],['Priya Patel','Court filing prep should be due today','1 urgent'],['Aaron Liu','Need client call follow-up added','1 open']] as const;
const feed = [['Acme v. Northline','Hearing prep milestone due in 2 days; red flag raised because research memo is incomplete.','2 days · Elena V.'],['Rao v. Harbor Transit','Discovery packet remains blocked awaiting client records.','1 day · Jasmin L.'],['Summit Logistics','Invoice follow-up overdue; client promised remittance this week.','Today · Billing'],['Al Noor Holdings','Opposing counsel sent revised position and response is not yet assigned.','Today · Marcus J.'],['Vega Arbitration','Mediation prep checklist is mostly complete, one witness outline still missing.','1 day · Priya P.'],['Riverside Foods','Ticket reopened after client said no update was received.','Today · Farah A.'],['North Shore','Template-driven intake tasks all green.','2 days · Intake'],['Bluewater','Potential matter moved to engagement review.','3 days · Marketing']] as const;
const growthBars = [3,3,4,2,3,5,3,3,3,2,4,0];
const hoursPeople = ['DK','JD','MJ','AL','TB','CM','CN'];

function RingCard({ title, value, subtitle, accent, breakdown }: typeof topCards[number]) {
  return <section className={`lex-card lex-card-compact accent-${accent}`}><div className="lex-card-head"><h3>{title}</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart"><div className="ring-hole"><strong>{value}</strong><span>ITEMS</span></div></div></div><div className="ring-meta"><div className="ring-label">{subtitle}</div><div className="legend-row">{breakdown.map((item) => <span key={item}>{item}</span>)}</div><div className="ring-foot">Operational snapshot</div></div></div></section>;
}

export default function HomePage() {
  return (
    <LexShell active="/" title="Today" subtitle="Sunday, April 26, 2026" actionLabel="Overview">
      <section className="lex-question-row"><div className="question-badge">1</div><div><h2>Are we on top of our cases?</h2><p>Operational R/Y/G across milestones, deadlines, hearings, capacity &amp; A/R</p></div></section>
      <section className="today-top-grid">{topCards.map((card) => <RingCard key={card.title} {...card} />)}</section>
      <section className="today-mid-grid"><section className="lex-card accent-red wide-panel"><div className="lex-card-head"><h3>Lawyer capacity</h3><span className="chev">›</span></div><div className="internal-card-body capacity-panel">{capacity.map(([name,pct]) => <div className="capacity-line" key={name}><span>{name}</span><div className="capacity-bar"><i style={{ width: `${pct}%` }} /></div><em>{pct}%</em></div>)}</div></section><section className="lex-card accent-amber narrow-panel"><div className="lex-card-head"><h3>A/R aging</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart money-ring"><div className="ring-hole"><strong>$2.0M</strong><span>A/R</span></div></div></div><div className="ring-meta stacked-meta"><span>0–30: $1.2M</span><span>31–60: $430k</span><span>61–90: $250k</span><span>90+: $120k</span></div></div></section></section>
      <section className="lex-question-row section-gap-top"><div className="question-badge">2</div><div><h2>Is the team doing what they’re supposed to do?</h2><p>Tasks, blocked items, accountability, and recent operational follow-through</p></div></section>
      <section className="today-bottom-grid"><section className="lex-card accent-red"><div className="lex-card-head"><h3>Tasks assigned</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart"><div className="ring-hole"><strong>33</strong><span>TASKS</span></div></div></div><div className="ring-meta stacked-meta"><span>11 overdue</span><span>0 due today</span><span>9 due soon</span><span>13 green</span></div></div></section><section className="lex-card accent-plain"><div className="lex-card-head"><h3>Recent tasks delegated</h3><span className="chev">›</span></div><div className="internal-card-body checklist-panel">{accountability.map(([owner, issue, meta]) => <div key={owner} className="checklist-row"><strong>{owner}</strong><p>{issue}</p><span>{meta}</span></div>)}</div></section><section className="lex-card accent-red"><div className="lex-card-head"><h3>Firmwide accountability</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart alert-ring"><div className="ring-hole"><strong>12</strong><span>FLAGS</span></div></div></div><div className="ring-meta stacked-meta"><span>8 red</span><span>3 yellow</span><span>1 green follow-up</span></div></div></section></section>
      <section className="feed-panel lex-card lex-card-compact accent-red"><div className="lex-card-head"><h3>Feed of accountability</h3><span className="feed-meta">Most recent first</span></div><div className="feed-list">{feed.map(([matter,detail,meta],i) => <div className={`feed-row ${i===3 || i===6 ? 'feed-row-warning' : ''}`} key={matter + meta}><div><strong>{matter}</strong><p>{detail}</p></div><span>{meta}</span></div>)}</div></section>

      <section className="lex-question-row section-gap-top"><div className="question-badge">3</div><div><h2>Are we growing and meeting our growth goals?</h2><p>New cases · net income · billable hours vs 40h goal</p></div></section>
      <section className="today-growth-top"><section className="lex-card accent-plain"><div className="lex-card-head"><h3>New cases this month</h3><span className="chev">›</span></div><div className="growth-gauge-card"><div className="half-gauge"><div className="half-gauge-inner"><strong>0</strong><span>/ 10</span><small>0% of goal</small></div></div><div className="gauge-meta"><span>Last month 2</span><span>QTD vs LY 0 vs 3</span></div></div></section><section className="lex-card accent-plain"><div className="lex-card-head"><h3>Net income · this quarter</h3><span className="chev">›</span></div><div className="income-card"><strong>$1.4M</strong><p>▲ 116% vs last Q ($666k)</p><div className="goal-line"><i style={{ width: '76%' }} /></div><div className="goal-meta"><span>Quarter goal: $1.25M</span><span>676%</span></div></div></section><section className="lex-card accent-plain"><div className="lex-card-head"><h3>Net income · YTD</h3><span className="chev">›</span></div><div className="income-card"><strong>$2.3M</strong><p>▲ 770% vs same point last year ($263k)</p><div className="goal-line"><i style={{ width: '86%' }} /></div><div className="goal-meta"><span>Year goal: $850k</span><span>249%</span></div></div></section></section>
      <section className="lex-card lex-card-compact accent-plain growth-bar-card"><div className="lex-card-head"><h3>New cases · last 12 months</h3><span className="feed-meta">Goal: 10/month</span></div><div className="months-bars">{growthBars.map((v,idx) => <div key={idx} className="month-bar-col"><div className="month-bar" style={{ height: `${22 + v*10}px` }} /><span>{['May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr'][idx]}</span></div>)}</div></section>
      <section className="today-growth-mid"><section className="lex-card accent-red"><div className="lex-card-head"><h3>Lawyers · hours vs 40h goal</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart alert-ring"><div className="ring-hole"><strong>8</strong><span>LAWYERS</span></div></div></div><div className="ring-meta stacked-meta"><span>8 under (&lt;90%)</span><span>0 over (&gt;110%)</span><span>0 on track</span></div></div></section><section className="lex-card accent-red"><div className="lex-card-head"><h3>Paralegals · hours vs 40h goal</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart alert-ring"><div className="ring-hole"><strong>4</strong><span>PARALEGALS</span></div></div></div><div className="ring-meta stacked-meta"><span>4 under (&lt;90%)</span><span>0 over (&gt;110%)</span><span>0 on track</span></div></div></section></section>
      <section className="lex-card lex-card-compact accent-plain projected-hours-card"><div className="lex-card-head"><h3>Projected weekly hours · per person</h3><span className="feed-meta">Bar &lt; 5 at 40h goal · click for drill-down</span></div><div className="projected-grid">{hoursPeople.map((p, i) => <div key={p} className="projected-row"><span>{p}</span><div className="projected-scale"><i style={{ width: `${35 + i*8}%` }} /></div><em>{[40,55,80,95,110][Math.min(4, Math.floor(i/2))]}%</em></div>)}</div></section>
      <section className="today-growth-bottom"><section className="lex-card accent-red"><div className="lex-card-head"><h3>Potentials</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart"><div className="ring-hole"><strong>9</strong><span>OPEN</span></div></div></div><div className="ring-meta stacked-meta"><span>6 red</span><span>2 yellow</span><span>2 green</span><span>$27.3M pipeline</span><span>5 need first outreach</span></div></div></section><section className="lex-card accent-plain"><div className="lex-card-head"><h3>New business · court watch</h3><span className="chev">›</span></div><div className="business-watch"><strong>11</strong><p>new filings to review</p><div className="business-color-bars"><span className="c-red">Mass tings</span><span className="c-blue">Bankruptcy</span><span className="c-amber">Commercial</span><span className="c-green">Real estate</span></div></div></section></section>

      <section className="lex-question-row section-gap-top"><div className="question-badge">4</div><div><h2>Am I moving the needle?</h2><p>My strategic projects to grow & improve the firm</p></div></section>
      <section className="today-growth-mid moving-needle-top"><section className="lex-card accent-red"><div className="lex-card-head"><h3>My strategic projects</h3><span className="chev">›</span></div><div className="lex-card-body"><div className="ring-wrap"><div className="ring-chart strategic-ring"><div className="ring-hole"><strong>16</strong><span>ACTIVE</span></div></div></div><div className="ring-meta stacked-meta"><span>6 at risk</span><span>4 watch</span><span>6 on track</span></div></div></section><section className="lex-card accent-plain"><div className="lex-card-head"><h3>By category</h3><span className="chev">›</span></div><div className="bars-list">{[['Marketing',6,4],['Business dev',4,3],['Hiring',2,2],['Operations',2,1],['Compliance',1,0],['Practice area',1,0]].map(([name,total,amber]) => <div key={String(name)} className="bars-row"><div className="bars-label"><span>{name}</span><em>{total}</em></div><div className="triple-bar"><i className="seg-red" style={{ width: `${Math.max(12, Number(total)*9)}%` }} /><i className="seg-amber" style={{ width: `${Number(amber)*12}%` }} /><i className="seg-green" style={{ width: `${Math.max(18, 100 - Number(total)*9 - Number(amber)*12)}%` }} /></div></div>)}</div></section><section className="lex-card accent-plain"><div className="lex-card-head"><h3>By strategic goal</h3><span className="chev">›</span></div><div className="bars-list">{[['Growth',7,2],['Brand',6,2],['Capacity',3,2],['Risk',1,0]].map(([name,total,amber]) => <div key={String(name)} className="bars-row"><div className="bars-label"><span>{name}</span><em>{total}</em></div><div className="triple-bar"><i className="seg-red" style={{ width: `${Math.max(12, Number(total)*11)}%` }} /><i className="seg-amber" style={{ width: `${Number(amber)*14}%` }} /><i className="seg-green" style={{ width: `${Math.max(16, 100 - Number(total)*11 - Number(amber)*14)}%` }} /></div></div>)}</div></section></section>
      <section className="lex-card lex-card-compact accent-plain strategic-feed-card"><div className="lex-card-head"><h3>Strategic projects at risk</h3><span className="feed-meta">View all →</span></div><div className="feed-list strategic-feed">{[['Plaintiff Outreach — Bankruptcy Trustees Campaign','Business dev · David Rodriguez','40% · 27d left'],['Florida UFTA Update — Blog Series','Marketing · Sarah Kim','33% · 30d left'],['Real Estate Practice Page Refresh','Marketing · Elena Vasquez','25% · 19d left'],['Q2 Bankruptcy Avoidance Webinar','Marketing · David Rodriguez','40% · 16d left'],['April Client Newsletter','Marketing · Priya Patel','60% · 5d overdue'],['Hire Litigation Paralegal (3rd seat)','Hiring · Margaret Chen','67% · 8d overdue']].map(([name,meta,status],i) => <div className={`feed-row ${i===0 || i===4 ? 'feed-row-warning' : ''}`} key={String(name)}><div><strong>{name}</strong><p>{meta}</p></div><span>{status}</span></div>)}</div></section>
      <section className="drill-into-row"><span>DRILL INTO</span><div className="drill-chips"><button>Milestones</button><button>By stage</button><button>Capacity</button><button>Hours</button><button>Strategic</button><button>Financials</button></div></section>

    </LexShell>
  );
}
